import type { Metadata } from "next";
import Link from "next/link";
import { Article, Clause, PageShell } from "@/components/shared/PageShell";
import { DISCLAIMER, SITE } from "@/lib/config";

export const metadata: Metadata = {
  title: "Terms",
  description:
    "Terms of use for Cooe: an informational AI service, provided without warranty and without professional advice.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <PageShell
      eyebrow="Terms"
      title="Terms of use."
      lede="By using Cooe you agree to what follows. It is short on purpose."
    >
      <Article>
        <Clause heading="What Cooe is">
          <p>
            Cooe is an informational tool that uses AI to describe how a message
            or situation may be interpreted, and to suggest wording. Everything
            it produces is a suggestion generated by a language model.
          </p>
        </Clause>

        <Clause heading="No guarantee of accuracy">
          <p>
            Output may be wrong, incomplete, or unsuited to your situation.
            Communication signal scores are heuristic estimates, not
            measurements, and are not scientifically validated. Cooe cannot know
            what another person thinks and does not predict how anyone will
            behave.
          </p>
        </Clause>

        <Clause heading="Not professional advice">
          <p>{DISCLAIMER}</p>
          <p>
            If you are dealing with a mental health concern, a legal matter, or
            a situation involving threats, intimidation or fear for your safety,
            contact a qualified professional or a local support service. Do not
            rely on Cooe for those.
          </p>
        </Clause>

        <Clause heading="Your responsibility">
          <p>
            You decide what to say and what to send. You are responsible for
            what you submit to Cooe and for anything you do with its output,
            including checking that it is appropriate before you use it.
          </p>
          <p>
            Do not submit other people&rsquo;s confidential information, or
            content you do not have the right to share.
          </p>
        </Clause>

        <Clause heading="Prohibited use">
          <p>
            Cooe may not be used to manipulate, coerce, threaten, harass,
            deceive, stalk, monitor, blackmail or humiliate anyone, or to
            pressure a person into contact, intimacy, money or commitment. It
            may not be used to generate content that is illegal or abusive.
          </p>
          <p>
            The service declines these requests, and using it for them is a
            breach of these terms.
          </p>
        </Clause>

        <Clause heading="Availability">
          <p>
            Cooe is in beta and provided &ldquo;as is&rdquo;, without warranties
            of any kind. It may change, break, or be unavailable, and features
            may be removed. To the extent permitted by law, no liability is
            accepted for loss arising from use of the service.
          </p>
        </Clause>

        <Clause heading="Future paid functionality">
          <p>
            Cooe is free during beta. Paid, pay-as-you-go functionality may be
            introduced later. No payment processing is active today, and any
            pricing, currencies and refund terms will be published before
            charging begins.
          </p>
        </Clause>

        <Clause heading="AI provider processing">
          <p>
            Text you submit is transmitted to a third-party AI provider for
            processing. See the{" "}
            <Link href="/privacy" className="underline underline-offset-4 hover:text-ink">
              privacy page
            </Link>{" "}
            for detail.
          </p>
        </Clause>

        <Clause heading="Contact">
          <p>
            Questions about these terms: {SITE.contactEmail}. The service is
            referred to throughout as Cooe.
          </p>
        </Clause>
      </Article>
    </PageShell>
  );
}
